url: http://sm.evg-soft.com
baseurl:

# Site settings
title: Evgsoft
email: info@evg-soft.com
description: "Smart-contract Development"

# Team names, titles and social links
people:
- name: Yevhen Bilous
  pic: andre
  position: Founder
  social:
    - title: github
      url: http://github.com/
    - title: twitter
      url: https://twitter.com/
    - title: linkedin
      url: https://www.linkedin.com/in/eugene_belous
    - title: file-o # Resume information
      url: http://XXXX.me/
  specialization: I create smart-contracts for Ethereum blockchain network.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/

# Postal address (add as many lines as necessary)
address:
  - line: Los Angeles

# Build settings
markdown: kramdown
permalink: pretty
port: 4001
